<?php

namespace Database\Seeders;

use App\Models\ModuleRubric;
use App\Models\Program;
use App\Models\ProgramModule;
use App\Models\ProgramModuleContent;
use App\Models\RubricItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuleRubricSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $program = Program::where('name', 'Maternal Health (EmONC)')->firstOrFail();

            foreach ($this->rubricData() as $entry) {
                $module = ProgramModule::where('program_id', $program->id)
                    ->where('name', 'like', "%{$entry['module']}%")
                    ->first();

                if (! $module) {
                    $this->command->warn("Module not found: {$entry['module']}");
                    continue;
                }

                // Seed case scenario as ProgramModuleContent
                if (! empty($entry['case_scenario'])) {
                    ProgramModuleContent::firstOrCreate(
                        [
                            'program_module_id' => $module->id,
                            'type' => 'case_scenario',
                            'title' => $entry['rubric_title'] . ' — Case Scenario',
                        ],
                        [
                            'content' => $entry['case_scenario'],
                            'order_sequence' => 1,
                            'is_active' => true,
                        ]
                    );
                }

                // Seed rubric definition
                $rubric = ModuleRubric::firstOrCreate(
                    [
                        'program_module_id' => $module->id,
                        'title' => $entry['rubric_title'],
                    ],
                    [
                        'description' => $entry['description'] ?? null,
                        'case_scenario' => $entry['case_scenario'] ?? null,
                        'total_marks' => $entry['total_marks'],
                        'pass_marks' => $entry['pass_marks'],
                        'pass_percentage' => $entry['pass_percentage'],
                        'equipment_supplies' => $entry['equipment'] ?? null,
                        'debrief_questions' => $entry['debrief'],
                        'order_sequence' => 1,
                        'is_active' => true,
                    ]
                );

                // Seed rubric items (idempotent by order_sequence within a rubric)
                foreach ($entry['items'] as $seq => $item) {
                    RubricItem::firstOrCreate(
                        [
                            'module_rubric_id' => $rubric->id,
                            'order_sequence' => $seq + 1,
                        ],
                        [
                            'description' => is_array($item) ? $item['text'] : $item,
                            'guidance' => is_array($item) ? ($item['guidance'] ?? null) : null,
                            'is_active' => true,
                        ]
                    );
                }

                $this->command->line("  ✓ {$entry['module']}: {$entry['total_marks']}-item rubric seeded.");
            }
        });

        $this->command->info('Module rubrics and case scenarios seeded successfully.');
    }

    private function rubricData(): array
    {
        return [

            // ─── MODULE 4: AMTSL ───────────────────────────────────────────────────────
            [
                'module' => 'Active Management of the Third Stage',
                'rubric_title' => 'AMTSL Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for Active Management of the Third Stage of Labour (AMTSL). Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "PATIENT: Natalie\n\nSCENARIO: Natalie was admitted to the labor ward in the second stage of labor and has had a normal vaginal birth.\n\nTASK: Manage the third stage of labor giving a running commentary.",
                'total_marks' => 21,
                'pass_marks' => 17,
                'pass_percentage' => 80.95,
                'equipment' => [
                    'Madam Zoe/Mama Natalie with placenta',
                    'AMTSL Job aid',
                    'Syringes 2cc and 5cc',
                    'Needle Size G 21 or 23',
                    'Large bore cannulas (G 16)',
                    'Oxytocin ampoule 10 IU',
                    'Foley\'s catheter',
                    'Antiseptic lotion, e.g. 5% chlorhexidine',
                    'Sterile gloves',
                    'Examination gloves',
                    'Blood collection drapes/calibrated blood collection device',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of AMTSL?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Explains the procedure and blood collection drape to the mother and birth companion',
                    'Obtains informed consent',
                    'Checks for a second baby',
                    'Tells the woman what medication she is being given and why',
                    'Gives uterotonic within 1 minute of birth of the baby',
                    'Unfolds the blood collection drape or places the blood collection device',
                    'Performs delayed cord clamping 1–3 minutes after giving uterotonics',
                    'Changes gloves before cutting the cord',
                    'Delivers placenta by controlled cord traction (CCT) while applying counter traction only when the mother is having a contraction',
                    'Uses both hands to receive the placenta while gently rotating it as it is being delivered',
                    'Inspects the placenta for completeness',
                    'Assesses fundal tone immediately following delivery of the placenta',
                    'Examines the birth canal for tears or lacerations',
                    'Assesses the amount of blood loss — checks the amount of blood collected in the drape or blood collection device AND vaginal blood flow',
                    'Demonstrates and asks the woman/birth companion to assess the uterus every 15 minutes for 2 hours and massage if soft until tone is achieved and to report any excessive bleeding',
                    'Monitors the mother by assessing blood volume in the drape, vaginal blood flow, uterine tone, pulse rate, and BP every 15 minutes for 2 hours after placenta delivery, then every 30 minutes for the next 4 hours; records on the blood loss monitoring chart for the first hour',
                    'Checks the baby\'s colour, temperature, and breathing; initiates skin-to-skin contact',
                    'Encourages breastfeeding within 1 hour of birth',
                    'Explains to the mother to frequently empty the bladder',
                    'Explains to the mother the results of the procedure',
                    'Documents all the procedures',
                ],
            ],

            // ─── MODULE 5: PPH FIRST RESPONSE BUNDLE ──────────────────────────────────
            [
                'module' => 'Management of Postpartum Hemorrhage',
                'rubric_title' => 'PPH First Response Bundle Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for the First Response Bundle for PPH treatment. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "PATIENT: Nancy\n\nSCENARIO: Nancy is a para 3+0. She just successfully delivered a live male infant who scored 10/10 at 1 and 5 minutes. Placenta was successfully delivered and complete. She has a history of prolonged labor.\n\nTASK: Please lead the emergency management of this client. You can ask for help from the other mentees as necessary.",
                'total_marks' => 20,
                'pass_marks' => 17,
                'pass_percentage' => 85.00,
                'equipment' => [
                    'Madam Zoe/Mama Natalie',
                    'Blood tank with blood',
                    'Calibrated drapes',
                    'PPH management Action Plan',
                    'PPH Kit',
                    'Syringes 2cc and 5cc',
                    'Needle Size 21 or 23',
                    '2 Large bore cannulas (G 16)',
                    'Speculums',
                    'Oxytocin ampoules',
                    'IV Tranexamic acid',
                    'Misoprostol tablets',
                    'Foley\'s catheter',
                    'Examination gloves',
                    'Infusion sets',
                    'Normal saline/Ringer\'s lactate',
                    'Sample collection bottles',
                    'Strapping',
                    'Blood collection drapes',
                    'Blood loss monitoring chart',
                    'MEOWS Chart',
                ],
                'debrief' => [
                    'How did the practical session feel?',
                    'What are the components of the first response bundle?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Shouts for help, quickly assembles the emergency team and asks for the PPH kit',
                    'The team lead assigns individual team members a role',
                    'The team leader reassures the mother and briefly explains what is going on as the other team members continue emergency management',
                    'Checks bleeding and amount of blood lost in the drape',
                    'Quickly assesses ABCs and resuscitates as necessary',
                    'Triggers the bundle — massages the uterus',
                    'Checks the bladder and catheterizes',
                    'Asks the assistant OR inserts 2 wide bore cannulas',
                    'Asks the assistant / collects blood samples: Complete blood count, grouping and cross match (GXM), U/E/C, coagulation profile',
                    'Infuses 10 IU Oxytocin in 500 ml of crystalloid over 10 minutes or as fast as possible, then 20 IU Oxytocin in 1 liter of crystalloid to run over 4 hours',
                    'Asks the assistant OR administers 800 µg misoprostol sublingually',
                    'Asks the assistant OR administers 1 g TXA at the rate of 1 ml per minute over 10 minutes',
                    'Gives IV fluids if clinically indicated',
                    'Asks the assistant / rechecks the uterus',
                    'Asks the assistant / checks for tears',
                    'Asks the assistant / checks the placenta for completeness',
                    'Once bleeding is controlled, monitors blood in drape, uterine tone, per vaginal bleeding, and vital signs (BP, Pulse) every 15 minutes for the first 2 hours, then every 30 minutes for the next 4 hours',
                    'Provides respectful care and good communication',
                    'Informs the mother of the management progress',
                    'Documents the findings/management including the blood loss monitoring chart',
                ],
            ],

            // ─── TRACK I: BIMANUAL COMPRESSION ────────────────────────────────────────
            [
                'module' => 'Bimanual compression of the uterus',
                'rubric_title' => 'Bimanual Compression of the Uterus — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for bimanual uterine compression as a PPH intervention. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "SCENARIO: You are managing PPH and you have used all the options available, but the uterus is still not contracted. You have decided to perform a bimanual uterine compression as a remedy.\n\nTASK: Give a running commentary as you perform the procedure.",
                'total_marks' => 12,
                'pass_marks' => 10,
                'pass_percentage' => 83.33,
                'equipment' => [
                    'Mama Natalie without placenta',
                    'Examination gloves',
                    'Syringes 2cc and 5cc',
                    'Needle Size 21 or 23',
                    'Large bore cannulas (G 16 or 18)',
                    'Oxytocin ampoule 10 IU',
                    'Foley\'s catheter',
                    'Antiseptic lotion e.g. 5% chlorhexidine',
                    'Bimanual compression Job aid',
                    'Sterile gloves',
                    'Gynecological gloves',
                    'Calibrated blood loss monitoring chart',
                    'Blood loss monitoring chart',
                    'MEOWS Chart',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of bimanual compression of the uterus?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Shouts for help',
                    'Briefly explains the procedure to the mother',
                    'Obtains informed consent',
                    'Performs hand hygiene and puts on gynecological gloves (double gloving)',
                    'Performs a vaginal examination',
                    'Inserts the whole hand into the vagina',
                    'With the hand in the vagina, identifies the anterior fornix',
                    'Forms a fist',
                    'Places the fist in the anterior wall of the uterus',
                    'With the other hand on the supra-pubic area, presses deeply into the abdomen behind the uterus, applying pressure against the posterior wall of the uterus (supra-pubic pressure)',
                    'Maintains pressure for at least 5 minutes until bleeding is controlled and uterus contracts while continuing with other PPH interventions',
                    'Explains to the mother the results of the procedure and next steps',
                ],
            ],

            // ─── TRACK II: COMPRESSION OF ABDOMINAL AORTA ────────────────────────────
            [
                'module' => 'Compression of abdominal aorta',
                'rubric_title' => 'Compression of Abdominal Aorta — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for abdominal aortic compression as a PPH intervention. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "SCENARIO: You are managing PPH and you have used all the options available, but the uterus is still not contracted. You have decided to perform compression of abdominal aorta as a remedy.\n\nTASK: Give a running commentary as you perform the procedure.",
                'total_marks' => 13,
                'pass_marks' => 10,
                'pass_percentage' => 76.92,
                'equipment' => [
                    'Madam Zoe without placenta',
                    'Gloves',
                    'Stretcher',
                    'Syringes 2cc and 5cc',
                    'Needle G 21 or 23',
                    'Large bore cannulas (G 16)',
                    'Antiseptic lotion e.g. 7.1% chlorhexidine',
                    'Oxytocin ampoule 10 IU',
                    'Blood loss monitoring chart',
                    'Calibrated blood loss drape',
                    'MEOWS Chart',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of compression of abdominal aorta?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Shouts for help',
                    'Briefly explains the procedure to the mother and obtains consent',
                    'Places the calibrated blood collection drape',
                    'Locates the femoral pulse',
                    'Places a closed fist above the umbilicus, slightly to the patient\'s left',
                    'Applies downward pressure through the abdominal wall to the abdominal aorta',
                    'With the other hand, palpates the femoral pulse to check the adequacy of the compression',
                    'Checks if pulse is present or not, and comments on the adequacy of the compression',
                    'Maintains compression until the bleeding is controlled or patient reaches the operation table',
                    'Monitors maternal vital signs and response to compression',
                    'Measures blood loss',
                    'Explains to the mother the results of the procedure and next steps',
                    'Documents the results',
                ],
            ],

            // ─── TRACK III: REMOVAL OF RETAINED PLACENTA ──────────────────────────────
            [
                'module' => 'Removal of retained placenta',
                'rubric_title' => 'Manual Removal of Retained Placenta — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for manual removal of retained placenta. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "PATIENT: Para 2+0, all SVD deliveries, minimal bleeding, normal vital signs. Baby scored well and is stable.\n\nSCENARIO: You are on duty and have been informed that it has been one hour since the patient gave birth, and the placenta has not been delivered.\n\nTASK: Using the mannequin provided, describe step by step how you will manually remove the placenta. Give a running commentary of the procedure.",
                'total_marks' => 23,
                'pass_marks' => 20,
                'pass_percentage' => 86.96,
                'equipment' => [
                    'Mama Natalie with placenta',
                    'Placenta model with cord attached',
                    'Pelvic model',
                    'Foley\'s catheter',
                    'Oxytocin',
                    'Cannulas',
                    'Gynecological gloves',
                    'Syringes',
                    'Needles',
                    'Antiseptic solution',
                    'Sterile vaginal examination pack',
                    'Intravenous fluids',
                    'IV giving set',
                    'Blood loss monitoring chart',
                    'Calibrated blood loss drapes',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of removal of retained placenta?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Ensures privacy',
                    'Explains procedure to the mother',
                    'Obtains informed consent',
                    'Places blood loss measuring drape',
                    'Inserts large bore IV lines if not in place',
                    'Takes blood samples and runs IV fluids',
                    'Performs hand hygiene and puts on sterile gloves',
                    'Inserts a Foley\'s catheter and empties bladder',
                    'Administers analgesics and antibiotics: Diazepam 10 mg IM/IV (if not in shock); 2 g Ampicillin IV or 1 g Cefazolin IV or IV Ceftriaxone 2 g plus IV Metronidazole 500 mg',
                    'Performs hand hygiene, wears PPE, and puts on gynecological gloves',
                    'Holds the umbilical cord with a clamp and gently pulls, using the cord to guide the other hand into the uterus',
                    'Places fingers of one hand into the uterus, follows the cord to locate the placenta, and identifies the edge of the placenta',
                    'Identifies the rough surface behind the placenta and carefully separates it from the uterine wall by smoothly sweeping fingers back and forth while stabilizing the uterine fundus with the other hand',
                    'Withdraws the hand, bringing the placenta with it, and provides counter traction abdominally',
                    'Once placenta is out, checks uterine tone and massages if soft',
                    'Examines the placenta for completeness',
                    'Performs exploration for any fragments',
                    'Removes fragments by hand, using ovum forceps or wide curette',
                    'Examines the cervix, vagina, and perineum for any tears and repairs accordingly',
                    'Gives oxytocin 20 IU in 1-liter normal saline at 60 drops/minute',
                    'States will check BP, pulse, and uterine tone every 15 minutes for 2 hours after placenta removal, then every 30 minutes until 6 hours postpartum',
                    'Explains to the mother the results of the procedure',
                    'Documents — blood loss monitoring chart; mentions surgical intervention (theater) if placenta remains adherent despite manual attempt',
                ],
            ],

            // ─── TRACK IV: UTERINE INVERSION ──────────────────────────────────────────
            [
                'module' => 'Uterine inversion',
                'rubric_title' => 'Manual Reduction of Inverted Uterus — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for manual reduction of uterine inversion. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "SCENARIO: You are on duty and have been informed by the midwife that while she was trying to deliver the placenta, the patient complained of very severe lower abdominal pain and a feeling of fullness inside the vagina. On abdominal examination the uterine fundus is not palpable and the placenta is not yet separated. Currently the patient has just minimal bleeding.\n\nTASK: Using the mannequin provided, describe step by step how you will manually reduce the uterus. Give a running commentary of the procedure.",
                'total_marks' => 25,
                'pass_marks' => 22,
                'pass_percentage' => 88.00,
                'equipment' => [
                    'Mama Natalie with placenta',
                    'Placenta model with cord attached',
                    'Pelvic model',
                    'Foley\'s catheter',
                    'Oxytocin',
                    'Cannulas',
                    'Ceftriaxone/Metronidazole IV',
                    'Gynecological gloves',
                    'Syringes',
                    'Needles',
                    'Antiseptic solution',
                    'Sterile vaginal examination pack',
                    'Intravenous fluids',
                    'IV giving set',
                    'Blood loss monitoring chart',
                    'Blood loss drape',
                    'MEOWS Chart',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of manual replacement of uterine inversion?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Shouts for help',
                    'Places blood monitoring drape',
                    'Assembles the emergency team and assigns roles',
                    'Performs a quick survey',
                    'Ensures privacy',
                    'Explains the procedure to the mother',
                    'Obtains informed consent',
                    'Assesses blood loss',
                    'Quickly assesses ABCs and resuscitates as necessary',
                    'Discontinues uterotonic drugs if any',
                    'Inserts 2 wide bore cannulas (gauge 16 or 18)',
                    'Takes blood: FHG, U/E/CR, GXM, and coagulation profile',
                    'Starts infusion of crystalloids: normal saline or Ringer\'s lactate',
                    'Inserts a Foley\'s catheter and empties bladder',
                    'Administers analgesics and antibiotics: 2 g Ampicillin IV or 1 g Cefazolin IV or IV Ceftriaxone 2 g plus IV Metronidazole 500 mg',
                    'Performs hand hygiene, wears PPE, and puts on gynecological gloves',
                    'Replaces the uterine fundus to its correct position',
                    'Manually removes the placenta/any remaining bits of the placenta',
                    'Commences oxytocin infusion after successful removal of the placenta: oxytocin 20 units in 1 L of normal saline to run over 4 hours',
                    'Examines the cervix, vagina, and perineum for any tears and repairs accordingly',
                    'Monitors uterine tone, per vaginal bleeding, and vital signs every 15 minutes for the first 2 hours, then every 30 minutes for the next 4 hours',
                    'Explains to the mother the results of the procedure',
                    'States patient should be taken promptly to the operating room for surgical correction under spinal or general anesthetic if manual reduction is unsuccessful',
                    'Informs client on the outcomes',
                    'Documents blood loss/procedure in the blood monitoring chart',
                ],
            ],

            // ─── TRACK V-A: UBT — CONDOM TAMPONADE ───────────────────────────────────
            [
                'module' => 'intrauterine balloon tamponade (condom tamponade)',
                'rubric_title' => 'Intrauterine Balloon Tamponade (Condom Method) — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for placement of the intrauterine balloon tamponade using the condom method. Each item is scored Yes (1) if performed to standard, No (0) if not. Pass score is ≥ 80%.',
                'case_scenario' => "SCENARIO: The final year midwifery students were managing a case of PPH that required placement of the intrauterine balloon tamponade. They were hesitant to perform the procedure.\n\nTASK: Demonstrate the procedure to the students on intrauterine balloon tamponade insertion, explaining every step to the students.",
                'total_marks' => 23,
                'pass_marks' => 19,
                'pass_percentage' => 80.00,
                'equipment' => [
                    'Mama U',
                    'Intrauterine balloon / Condom tamponade',
                    'String',
                    'Clamp',
                    'Foley\'s catheter',
                    'Giving set',
                    'Water / Normal saline',
                    'Syringe',
                    'Gloves',
                    'Sim\'s speculum',
                    'Ovum forceps',
                    'Oxytocin',
                    'Broad spectrum antibiotics',
                    'Blood loss monitoring chart',
                    'MEOWS chart',
                    'Calibrated blood loss drape',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of placement of the balloon tamponade?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Briefly explains the procedure to the mother',
                    'Obtains informed consent',
                    'Wears sterile gloves',
                    'Assesses blood loss',
                    'Places balloon over the end of Foley\'s catheter',
                    'Ties lower end of balloon tightly below level of the balloon using suture/string — tight enough to prevent leakage but does not strangulate catheter',
                    'Inflates the urinary catheter balloon with about 20 cc of water',
                    'Places the Sim\'s speculum into the vagina and identifies the cervix',
                    'Grasps the anterior aspect of the cervix with ovum forceps',
                    'Aseptically places the end of the balloon high into the uterus with forceps, ensuring the entire balloon is above the cervical OS',
                    'Connects Foley\'s catheter to IV set connected to a 1-liter infusion bag and rapidly inflates balloon with 300–500 ml of saline until bleeding stops',
                    'Clamps catheter when desired volume is achieved and bleeding is controlled',
                    'Mentions: maintain balloon in situ for 24 hours after bleeding is controlled and patient is stable',
                    'Mentions: give oxytocin 20 IU in 1-liter normal saline at 60 drops/minute',
                    'States: give broad spectrum antibiotic',
                    'Monitors vital signs, uterine tone, bleeding, and urinary output every 15 minutes for first 2 hours, then every 30 minutes until 6 hours postpartum',
                    'Mentions: when patient is stable (after 24 hours), slowly deflate balloon by letting out 50 ml of water/saline every hour',
                    'Mentions: re-inflate with 50 ml to previous level if bleeding resumes on deflation',
                    'Mentions: balloon may be kept in place for up to 24 hours',
                    'Mentions: if bleeding not controlled within 15 minutes (or sooner if hemodynamically unstable or heavy bleeding), abandon procedure and seek surgical intervention immediately',
                    'Mentions: transfuse if indicated',
                    'Explains the results of the procedure to the mother',
                    'Documents the procedure findings, balloon volume, and monitoring outcomes',
                ],
            ],

            // ─── TRACK V-B: UBT — FREE FLOW SYSTEM ───────────────────────────────────
            [
                'module' => 'intrauterine balloon tamponade (free flow system)',
                'rubric_title' => 'Intrauterine Balloon Tamponade (Free Flow System) — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for placement of the intrauterine balloon tamponade using the free flow system. Each item is scored Yes (1) if performed to standard, No (0) if not. Pass score is > 85%.',
                'case_scenario' => "SCENARIO: The final year midwifery students were managing a case of PPH that required placement of the free flow system intrauterine balloon tamponade. They were hesitant to perform the procedure.\n\nTASK: Demonstrate the procedure to the students on the free flow system intrauterine balloon tamponade insertion, explaining every step to the students.",
                'total_marks' => 34,
                'pass_marks' => 30,
                'pass_percentage' => 85.00,
                'equipment' => [
                    'Mama U',
                    'Intrauterine balloon (free flow system)',
                    'Drip stand',
                    '1 liter of sterile water or normal saline',
                    'Foley\'s catheter and urine bag',
                    'Antiseptic solution',
                    'Sterile gloves',
                    'Sim\'s speculum',
                    'Ovum/sponge holding or Kelly\'s forceps',
                    'Uterotonics',
                    'Sanitary pad',
                    'Broad spectrum antibiotics',
                    'Syringes 2cc and 5cc',
                    'Needle gauge 21 or 23',
                    'Blood loss monitoring chart',
                    'Blood collection drapes',
                    'MEOWS Chart',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of placement of the free flow balloon tamponade?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Shouts for help',
                    'Obtains informed consent',
                    'Ensures blood collection drape is in situ',
                    'Wears sterile gloves',
                    'Assembles the free flow system (FFS) UBT by filling the supply bag with 1 liter of sterile water or normal saline; hangs supply bag on drip stand with T-valve closed',
                    'Positions the patient in dorsal or lithotomy position',
                    'Cleans the vulva and perineum with an antiseptic solution',
                    'Catheterizes the mother and ensures the bladder is empty; leaves catheter in situ for monitoring urine output',
                    'Drapes the patient using sterile drapes',
                    'Introduces the Sim\'s speculum to visualize the cervix',
                    'Applies 2 sponge holding or Kelly\'s forceps to the anterior lip of the cervix to stabilize the uterus by applying gentle traction',
                    'Removes the Sim\'s speculum',
                    'Introduces the balloon unit into the uterus (by hand or instrumental insertion) and gently advances the balloon high into the uterine cavity to reach the fundus',
                    'Gently withdraws the forceps to release the anterior lip of the cervix, leaving the balloon unit in position within the uterus',
                    'Positions 2 fingers (index and middle) at the cervix to maintain the balloon unit in position and prevent expulsion when inflating',
                    'Opens the T-valve to allow water to flow into the balloon from the water bag by gravity; continues to inflate while keeping 2 fingers in place and checking balloon remains secured within the uterine cavity',
                    'Allows water to flow until the flow stops to indicate equilibrium with the uterine cavity',
                    'Removes the 2 fingers at the cervix and waits for 2 minutes after inflation; rechecks whether the balloon remains in the uterine cavity',
                    'Sets the appropriate height for the supply bag based on the patient\'s systolic BP: 60 mmHg (0.8 m), 80 mmHg (1.1 m), 100 mmHg (1.3 m), 120 mmHg (1.6 m) from T-valve towards supply bag',
                    'Keeps T-valve open and notes the level of water in the bag when bleeding ceases',
                    'Checks to see if the patient is comfortable by asking her',
                    'Tapes the tubing to the patient\'s thigh to secure it; leaves enough leeway to allow for movement',
                    'Administers broad-spectrum IV antibiotic',
                    'Documents the time of insertion and records the total volume of water inflated into the balloon and the level in the bag',
                    'Continues with IV fluid resuscitation and uterotonic treatment',
                    'Continues to monitor the patient closely for active bleeding: vital signs (BP, Pulse, RR) every 15 minutes for first hour, 30 minutes for second hour, then hourly thereafter',
                    'Confirms the criteria for removal: 6–8 hours to allow physiological contraction and relaxation of the uterus; or after maximum 24 hours when patient is stable; leaves tamponade in situ if bleeding resumes on deflation',
                    'Drains water from the balloon tamponade into the water bag by positioning water bag at the same level as or lower than the patient with T-valve open (60 seconds)',
                    'When all water has drained out of the balloon (1 liter of fluid in supply bag), removes the balloon by gently pulling on the tubing',
                    'Observes closely for resumption of active bleeding during decompression of the balloon',
                    'After balloon tamponade removal, confirms haemostasis and re-inflates if bleeding resumes',
                    'Documents procedure findings and all outcomes in client record',
                    'Explains the procedure outcome in a respectful way; listens and responds attentively to the patient\'s questions and concerns; guides on need for completing the course of antibiotics',
                    'Continues monitoring post-removal: vital signs and vaginal bleeding at regular intervals',
                ],
            ],

            // ─── TRACK VI: REPAIR OF PERINEAL TEAR ───────────────────────────────────
            [
                'module' => 'Repair of perineal tear',
                'rubric_title' => 'Repair of Perineal Tear — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for repair of perineal tear. Each item is scored Yes (1) if performed to standard, No (0) if not. Items 17–20 assess key counseling messages delivered to the mother.',
                'case_scenario' => "PATIENT: Mary, a primigravida\n\nSCENARIO: Mary had precipitate labor and delivered a live male infant weighing 4 kg. She subsequently started bleeding profusely. On examination, a perineal tear is identified.\n\nTASK: Using the mannequin provided, demonstrate how to repair a perineal tear.",
                'total_marks' => 20,
                'pass_marks' => 17,
                'pass_percentage' => 85.00,
                'equipment' => [
                    'Laerdal perineal repair trainer',
                    'Sultan anal sphincter repair trainer',
                    'Suture pack',
                    'Sterile VE pack',
                    'Blood monitoring chart',
                    'Blood loss collection drapes',
                    'Sterile gowns',
                    'Sterile gloves',
                    'Needle holder',
                    'Non-toothed tissue holding forceps',
                    'Two retractors',
                    'Two Allis forceps',
                    'Suture material — absorbable suture 2/0 on a 35 mm round needle',
                    'Sterile 10/20 ml syringe and 21g needle',
                    'Local anesthetic: Lignocaine Hydrochloride Injection BP 1% (10–20 ml)',
                    'Portable light for visibility',
                    'Sterile gauze',
                    'Antibiotics',
                    'Stool softeners',
                ],
                'debrief' => [
                    'How did the practical session feel?',
                    'State the steps of perineal tear repair.',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Briefly explains the procedure to the patient',
                    'Obtains informed consent',
                    'Ensures blood collection drape is in place',
                    'Places woman in high lithotomy position and ensures proper lighting',
                    'Performs hand hygiene and puts on sterile gloves',
                    'Aseptically cleans the vulva',
                    'Drapes the patient and catheterizes',
                    'Infiltrates the perineum with local anesthesia and examines the perineal tear',
                    'Classifies the perineal tear (1st, 2nd, 3rd, or 4th degree); notes that 3rd, 4th degree and buttonhole tears should be repaired in theater under regional or general anesthesia',
                    'Places sterile gauze to collect lochia loss and improve visibility',
                    'Identifies the apex of vaginal trauma and inserts first stitch 5–10 mm above this point',
                    'Sutures posterior vaginal trauma and hymen remnants using a loose continuous non-locking stitch',
                    'Brings needle through tissue underneath the hymen ring and continues to repair deep and superficial perineal muscles using a loose continuous stitch, sealing any dead space to avoid haematoma',
                    'Apposes skin edges and completes the perineal repair',
                    'Completes the subcutaneous repair to the hymen ring; swings needle under tissue into the vagina and completes repair using a terminal loop knot',
                    'Explains to the mother the results of the procedure',
                    'Counsels on perineal hygiene',
                    'Provides sex education — timing of resumption',
                    'Advises on drug compliance (full course of antibiotics and analgesics)',
                    'Advises on pelvic muscle exercises and recommends hospital delivery for 3rd and 4th degree tears at a CEmONC facility',
                ],
            ],

            // ─── TRACK VII: REPAIR OF CERVICAL TEAR ──────────────────────────────────
            [
                'module' => 'Repair of cervical tear',
                'rubric_title' => 'Repair of Cervical Tear — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for repair of cervical tear. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "SCENARIO: You are called to examine a patient with PPH. On examination, the uterus is well contracted and the placenta was successfully delivered and complete. You confirm a cervical tear.\n\nTASK: Using the mannequin provided, demonstrate how to locate and repair a cervical tear.",
                'total_marks' => 18,
                'pass_marks' => 16,
                'pass_percentage' => 88.89,
                'equipment' => [
                    'Cervical model for repair',
                    'Suture pack',
                    'Sterile VE pack',
                    'Sterile gowns',
                    'Sterile gloves',
                    'Needle holder',
                    'Straight scissors',
                    'Two retractors',
                    'Two Allis forceps / Two sponge holding forceps',
                    'Suture material — absorbable suture Vicryl 0, 1, 2 with round body needle on 35 mm round body needle',
                    'Straight forceps',
                    'Blood monitoring chart',
                    'Blood loss collection drape',
                    'Sterile 10/20 ml syringe and 21g needle',
                    'Local anesthetic: Lignocaine Hydrochloride Injection BP 1% (10–20 ml)',
                    'Portable light for visibility',
                    'Infection prevention and control equipment and supplies',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of repair of cervical tear?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Briefly explains the procedure to the mother',
                    'Obtains informed consent and gives analgesics and antibiotics',
                    'Ensures blood collection drape is in situ',
                    'Places the woman in high lithotomy position',
                    'Cleans the perineum, vulva, and vagina with antiseptic',
                    'Inserts a catheter to empty the bladder',
                    'Administers regional anesthesia/sedation (Ketamine hydrochloride or diazepam)',
                    'Examines clockwise: peri-urethral area, perineum, vaginal opening, vagina, and cervix',
                    'Identifies the cervical tear and applies local anesthetic agent',
                    'Grasps the cervix on one side of the tear with the first sponge forceps',
                    'Grasps the other side of the cervical tear with second sponge forceps',
                    'Gently pulls the cervix and rotates the sponge forceps to locate the tip of the tear',
                    'After identifying the tip, places both forceps in one hand',
                    'Places the first suture above the tip of the tear, then places 2 more continuous sutures',
                    'Uses continuous sutures to complete repair',
                    'Wipes off any visible blood and confirms haemostasis; notes that if haemostasis is not achieved, take patient to theater',
                    'Explains the results of the procedure to the mother',
                    'Documents results and blood monitoring chart',
                ],
            ],

            // ─── TRACK VIII: B-LYNCH SUTURE ───────────────────────────────────────────
            [
                'module' => 'B-Lynch suture',
                'rubric_title' => 'Placement of the B-Lynch Suture — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for placement of the B-Lynch suture for uterine atony. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "SCENARIO: You are the consultant on call. You are urgently called to the theater to attend to a patient with uterine atony. You arrive in theater just as the patient is being wheeled in. You placed a B-Lynch suture in the uterus which stopped the bleeding. After the patient was successfully reversed and stable, the interns want you to slowly demonstrate how to insert the B-Lynch suture.\n\nTASK: Using the hood (uterine model) provided, demonstrate giving a running commentary on how to insert the B-Lynch suture.",
                'total_marks' => 23,
                'pass_marks' => 20,
                'pass_percentage' => 86.96,
                'equipment' => [
                    'Kofia (hood) — the uterine model',
                    'Sutures (Vicryl) size 0, 1, 2 round body',
                    'Needle holders',
                    'Sterile gloves',
                    'Scissors',
                    'Blood monitoring chart',
                    'Blood collection drape',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of placement of the B-Lynch suture?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Briefly explains the procedure to the mother/family',
                    'Mentions that the patient is given anesthesia in supine position',
                    'Mentions that s/he has scrubbed, the abdomen is clean and draped',
                    'Takes the vital signs (BP, respiratory rate, pulse rate)',
                    'Confirms IV access is established and blood products/cross-match are available',
                    'Mentions that the abdomen is opened',
                    'Mentions that the uterus is identified',
                    'Mentions that the uterus is assessed for atony and a decision to place a B-Lynch suture is made',
                    'Makes a lower uterine segment incision',
                    'Removes any placental tissue or products of conception',
                    'Starts from the right side (if right-handed) using a round-bodied large needle',
                    'Inserts the compression suture starting from the lower edge of the lower segment uterine incision, exits on the upper edge',
                    'Passes the suture over the fundus, enters the uterine cavity posteriorly at the level of the lower segment incision',
                    'Passes the suture horizontally to the left lower uterine and exits posteriorly',
                    'Passes the suture round over the fundus anteriorly to the upper edge of the left side of the incision, then exits from the lower edge',
                    'Asks assistant to compress the uterus',
                    'Pulls the two ends and ties them together',
                    'Performs bimanual compression to confirm adequate haemostasis before proceeding to uterine closure',
                    'Asks an assistant to confirm that vaginal bleeding is controlled',
                    'Mentions that the uterine incision is closed',
                    'Mentions that if bleeding does not stop, proceed to perform a hysterectomy',
                    'Explains the results of the procedure to the mother/family',
                    'Documents the results and blood loss monitoring chart',
                ],
            ],

            // ─── TRACK IX: NASG ───────────────────────────────────────────────────────
            [
                'module' => 'Placement of non-pneumatic anti-shock garment',
                'rubric_title' => 'Placement of the Non-Pneumatic Anti-Shock Garment (NASG) — Practical Assessment Rubric',
                'description' => 'Hands-on practical rubric for NASG placement and removal in a patient with PPH being prepared for referral. Each item is scored Yes (1) if performed to standard, No (0) if not.',
                'case_scenario' => "PATIENT: Madam Alwala, aged 35, para 5+0 Gravida 6\n\nSCENARIO: Madam Alwala was admitted at 6 am in labour at a health center and delivered at 2 pm a healthy baby boy (4.5 kg) who scored well. Thirty minutes after childbirth, during handover shift, the nurses discover she is in a pool of blood, confused, and agitated.\n\nTASK: With the aid of a NASG, demonstrate the management of the patient as she is prepared for referral/advanced care.",
                'total_marks' => 20,
                'pass_marks' => 17,
                'pass_percentage' => 85.00,
                'equipment' => [
                    'Non-pneumatic anti-shock garment',
                    'Clean gloves',
                    'Couch',
                    'BP machine',
                    'Timing device',
                ],
                'debrief' => [
                    'How did the assessment feel?',
                    'What are the steps of placing the non-pneumatic anti-shock garment?',
                    'Which steps did you perform well?',
                    'Which steps need to be improved?',
                ],
                'items' => [
                    'Briefly explains the procedure to the mother',
                    'Obtains informed consent',
                    'Ensures infection prevention is adhered to (clean gloves, clean environment)',
                    'Checks vital signs (BP, pulse, respiratory rate)',
                    'Places the woman correctly on the open NASG: top edge at lowest rib, pressure ball over umbilicus, dotted line between segments 5 and 6 aligned with the spine',
                    'Starts application from segment pair 1; folds segment 1 into 2 and starts application from segment 2',
                    'Performs snap test for segment 2: places 1–2 fingers under top of NASG segment, pulls back fabric and lets go — tight enough when it sounds like snapping fingers',
                    'Continues to close segment pairs 2 to 3 and performs snap test for each',
                    'Brings legs together and applies segment 4 around the woman\'s pelvis (does not snap)',
                    'Places segment 5 with pressure ball over umbilicus',
                    'Places segment 6 over segment 5 to close',
                    'Ensures woman can breathe normally: observes breathing, slides hand under NASG on abdomen to accommodate hand; slightly loosens segments 5 and 6 to support the pressure ball if needed',
                    'Continues with other relevant PPH management (IV fluids, uterotonics, blood if available)',
                    'Monitors closely for shortness of breath and decreased urine output during NASG use',
                    'Arranges prompt referral/transfer to higher level of care while NASG is in situ',
                    'Takes pulse rate and BP as baseline just before opening first segment for NASG removal',
                    'Opens segment pair 1 (or 2 for short women) to begin removal',
                    'Explains the outcome of the procedure to the patient',
                    'Documents the results and blood loss monitoring chart',
                    'Ensures handover communication at referral facility — conveys management given, NASG use, blood loss, and current vital signs',
                ],
            ],

        ];
    }
}
